name: ProSites
favicon: null
layout_spectrum: 0.4514308972284198
typography_spectrum: 0.7330074750352651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2660910105332732
  lightness: 0.3347276630811393
  saturation: 0.35423207515850663
  rhythmicContrast: 0.7102374397218227
purpose: []
